sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    # disable prompts for use of GCP CLI interactivity w/ Travis
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # build google cloud sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install kubectl in travis environment
  - gcloud components update kubectl
  # gives credentials to google cloud account
  - gcloud auth activate-service-account --key-file service-account.json
  # configure gcloud with project specs
  - gcloud config set project chowsafely-v3-216504
  - gcloud config set compute/zone us-west1-b
  - gcloud container clusters get-credentials chow-cluster
  # log in to docker w/ credentials
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master