apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: chowsafely-tls
spec:
  secretName: chowsafely
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: chowsafely.com
  dnsNames:
    - chowsafely.com
    - www.chowsafely.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - chowsafely.com
          - www.chowsafely.com