apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: lhemenez/web
          ports:
            - containerPort: 8000
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: client-id
                  key: CLIENT_ID
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key
                  key: API_KEY
            - name: USERNAME 
              valueFrom:
                secretKeyRef:
                  name: username
                  key: USERNAME